"""Generate the shared MICRO RETRO DODGEBALL UI font at Genesis 4bpp."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "ui_tiles.inc"

FONT = {
    "A":("01110","10001","10001","11111","10001","10001","10001"),
    "B":("11110","10001","10001","11110","10001","10001","11110"),
    "C":("01111","10000","10000","10000","10000","10000","01111"),
    "D":("11110","10001","10001","10001","10001","10001","11110"),
    "E":("11111","10000","10000","11110","10000","10000","11111"),
    "F":("11111","10000","10000","11110","10000","10000","10000"),
    "G":("01111","10000","10000","10111","10001","10001","01111"),
    "H":("10001","10001","10001","11111","10001","10001","10001"),
    "I":("11111","00100","00100","00100","00100","00100","11111"),
    "J":("00111","00010","00010","00010","10010","10010","01100"),
    "K":("10001","10010","10100","11000","10100","10010","10001"),
    "L":("10000","10000","10000","10000","10000","10000","11111"),
    "M":("10001","11011","10101","10101","10001","10001","10001"),
    "N":("10001","11001","10101","10011","10001","10001","10001"),
    "O":("01110","10001","10001","10001","10001","10001","01110"),
    "P":("11110","10001","10001","11110","10000","10000","10000"),
    "Q":("01110","10001","10001","10001","10101","10010","01101"),
    "R":("11110","10001","10001","11110","10100","10010","10001"),
    "S":("01111","10000","10000","01110","00001","00001","11110"),
    "T":("11111","00100","00100","00100","00100","00100","00100"),
    "U":("10001","10001","10001","10001","10001","10001","01110"),
    "V":("10001","10001","10001","10001","10001","01010","00100"),
    "W":("10001","10001","10001","10101","10101","10101","01010"),
    "X":("10001","10001","01010","00100","01010","10001","10001"),
    "Y":("10001","10001","01010","00100","00100","00100","00100"),
    "Z":("11111","00001","00010","00100","01000","10000","11111"),
    "0":("01110","10001","10011","10101","11001","10001","01110"),
    "1":("00100","01100","00100","00100","00100","00100","01110"),
    "2":("01110","10001","00001","00010","00100","01000","11111"),
    "3":("11110","00001","00001","01110","00001","00001","11110"),
    "4":("00010","00110","01010","10010","11111","00010","00010"),
    "5":("11111","10000","10000","11110","00001","00001","11110"),
    "6":("01110","10000","10000","11110","10001","10001","01110"),
    "7":("11111","00001","00010","00100","01000","01000","01000"),
    "8":("01110","10001","10001","01110","10001","10001","01110"),
    "9":("01110","10001","10001","01111","00001","00001","01110"),
    ":":("00000","00100","00100","00000","00100","00100","00000"),
    "-":("00000","00000","00000","11111","00000","00000","00000"),
    "/":("00001","00010","00010","00100","01000","01000","10000"),
    "<":("00010","00100","01000","10000","01000","00100","00010"),
    ">":("01000","00100","00010","00001","00010","00100","01000"),
    "!":("00100","00100","00100","00100","00100","00000","00100"),
    ".":("00000","00000","00000","00000","00000","00100","00100"),
    "?":("01110","10001","00001","00010","00100","00000","00100"),
}

ORDER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789:-/<>!.?"
FACES = (15, 6, 12)  # white, gold, cyan; outline/shadow is navy index 4


def encode(px, x0=0, y0=0):
    out = []
    for y in range(y0, y0 + 8):
        value = 0
        for x in range(x0, x0 + 8): value = (value << 4) | px[y][x]
        out.append(value)
    return out


def small(ch, face):
    px = [[0] * 8 for _ in range(8)]
    rows = FONT[ch]
    # Navy one-pixel drop shadow, then the brighter face.
    for y, row in enumerate(rows):
        for x, bit in enumerate(row):
            if bit == "1" and x + 2 < 8 and y + 1 < 8: px[y + 1][x + 2] = 4
    for y, row in enumerate(rows):
        for x, bit in enumerate(row):
            if bit == "1": px[y][x + 1] = face
    return encode(px)


def big(ch, face):
    px = [[0] * 16 for _ in range(16)]
    mask = [[False] * 16 for _ in range(16)]
    for sy, row in enumerate(FONT[ch]):
        for sx, bit in enumerate(row):
            if bit == "1":
                for yy in range(2):
                    for xx in range(2): mask[sy * 2 + yy][2 + sx * 2 + xx] = True
    for y in range(16):
        for x in range(16):
            if mask[y][x]: px[y][x] = face
    return [encode(px, tx * 8, ty * 8) for tx in range(2) for ty in range(2)]


small_tiles = [small(ch, face) for face in FACES for ch in ORDER]
# Large glyphs are authored once in colour index 15. Their tilemap palette
# chooses white/gold/cyan at draw time, avoiding three redundant 176-tile copies.
big_tiles = [tile for ch in ORDER for tile in big(ch, 15)]

lines = [
    "/* Generated by tools/build_ui_tiles.py. */",
    f"#define UI_GLYPH_COUNT {len(ORDER)}",
    f"#define UI_SMALL_TILE_COUNT {len(small_tiles)}",
    f"#define UI_BIG_TILE_COUNT {len(big_tiles)}",
    f'static const char ui_glyph_order[] = "{ORDER}";',
    "static const u32 ui_small_tiles[UI_SMALL_TILE_COUNT][8] = {",
]
for tile in small_tiles:
    lines.append("    { " + ", ".join(f"0x{v:08x}" for v in tile) + " },")
lines.append("};")
lines.append("static const u32 ui_big_tiles[UI_BIG_TILE_COUNT][8] = {")
for tile in big_tiles:
    lines.append("    { " + ", ".join(f"0x{v:08x}" for v in tile) + " },")
lines.append("};")
OUTPUT.write_text("\n".join(lines) + "\n", encoding="ascii")
print(f"Wrote {OUTPUT} ({len(small_tiles) + len(big_tiles)} tiles)")
