"""Build ROM-resident recoloured player poses for GLOBAL ELIMINATOR.

The game cannot afford to remap 32x32 sprite pixels during live gameplay.
This converts the authored Exhibition player tile blocks ahead of time into
the four palette-index variants shared across PAL1/PAL2/PAL3.  The source's
black ink (index 15) must remain fixed: remapping it as a kit shade destroys
the hair, boots and silhouette outline.
"""
from pathlib import Path
import re

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "player_isometric_tiles.inc"
OUTPUT = ROOT / "src" / "eliminator_variant_tiles.inc"
PREVIEW = ROOT / "assets" / "eliminator_player_preview.png"

POSES = [
    "tile_iso_front_stand",
    "tile_iso_front_run",
    "tile_iso_front_run_pass",
    "tile_iso_front_run_alt",
    "tile_iso_front_throw",
    "tile_iso_front_pickup",
    "tile_iso_front_hit",
    "tile_iso_front_fall",
    "tile_iso_front_celebrate",
    "tile_iso_back_stand",
    "tile_iso_back_run",
    "tile_iso_back_run_pass",
    "tile_iso_back_run_alt",
    "tile_iso_back_throw",
    "tile_iso_back_hit",
    "tile_iso_back_fall",
    "tile_iso_back_celebrate",
]

# Spain/variant-zero QA palette. Runtime supplies the same fixed colours and
# swaps only indices 8/9 per country and palette line.
PREVIEW_COLOURS = {
    0: (24, 40, 72), 1: (0xE1, 0xA4, 0x8E),
    2: (0xD2, 0x77, 0x5A), 3: (0xBA, 0x70, 0x61),
    4: (0xCA, 0x5B, 0x18), 5: (0x87, 0x50, 0x51),
    6: (0x95, 0x3C, 0x20), 7: (0x18, 0x18, 0x20),
    8: (0xCF, 0x82, 0x88), 9: (0x73, 0x2C, 0x32),
}


def colour_index(source: int, variant: int) -> int:
    kit_light = 8 + variant * 2
    kit_dark = kit_light + 1

    # Seven fixed colour slots must represent eight Exhibition colours. Merge
    # only the deepest brown shadow (11) with black ink (15); both become the
    # shared near-black outline.  Every authored contour and shoe pixel is then
    # preserved instead of accidentally becoming the country's darkest kit.
    fixed = {0: 0, 1: 1, 3: 2, 4: 3, 8: 4, 9: 5, 10: 6,
             11: 7, 15: 7}
    if source in fixed:
        return fixed[source]
    # The current authored 32x32 poses put most jersey highlights in index 12
    # (rather than index 2 as the earlier art did). Sending 12 to the dark/trim
    # slot flattened almost every athlete to one colour and made Brazil green.
    # Preserve a clear two-tone primary ramp across every front/back pose.
    if source in (2, 5, 6, 12):
        return kit_light
    return kit_dark


def remap_word(word: int, variant: int) -> int:
    result = 0
    for shift in range(28, -1, -4):
        result |= colour_index((word >> shift) & 0xF, variant) << shift
    return result


def read_pose(text: str, name: str) -> list[int]:
    match = re.search(
        rf"static const u32 {re.escape(name)}\[16\]\[8\] = \{{(.*?)\n\}};",
        text,
        re.S,
    )
    if not match:
        raise RuntimeError(f"Could not find 16x8 pose {name}")
    words = [int(value, 16) for value in re.findall(r"0x[0-9a-fA-F]+", match.group(1))]
    if len(words) != 128:
        raise RuntimeError(f"{name} contains {len(words)} words, expected 128")
    return words


def render_pose(words: list[int]) -> Image.Image:
    image = Image.new("RGB", (32, 32), PREVIEW_COLOURS[0])
    pixels = image.load()
    for tile in range(16):
        tx, ty = tile // 4, tile % 4  # VDP column-major tile order
        for row, word in enumerate(words[tile * 8:(tile + 1) * 8]):
            for column, shift in enumerate(range(28, -1, -4)):
                colour = colour_index((word >> shift) & 0xF, 0)
                if colour:
                    pixels[tx * 8 + column, ty * 8 + row] = PREVIEW_COLOURS[colour]
    return image


def main() -> None:
    text = SOURCE.read_text(encoding="utf-8")
    poses = [read_pose(text, name) for name in POSES]
    lines = [
        "/* Generated by tools/build_eliminator_variants.py. */",
        "#define ELIM_POSE_COUNT 17",
        "static const u32 tile_elim_variants[4][ELIM_POSE_COUNT][16][8] = {",
    ]
    for variant in range(4):
        lines.append("    {")
        for pose in poses:
            lines.append("        {")
            for tile in range(16):
                words = pose[tile * 8:(tile + 1) * 8]
                encoded = ", ".join(f"0x{remap_word(word, variant):08x}" for word in words)
                lines.append(f"            {{ {encoded} }},")
            lines.append("        },")
        lines.append("    },")
    lines.append("};")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    preview = Image.new("RGB", (9 * 40, 2 * 40), PREVIEW_COLOURS[0])
    for index, pose in enumerate(poses):
        x = 4 + (index % 9) * 40
        y = 4 + (index // 9) * 40
        preview.paste(render_pose(pose), (x, y))
    preview.resize((720, 160), Image.Resampling.NEAREST).save(PREVIEW)
    print(f"Wrote {OUTPUT}")
    print(f"Wrote {PREVIEW}")


if __name__ == "__main__":
    main()
