"""Generate ten 16x8 national flags as Genesis 4bpp tile data."""

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "flag_tiles.inc"
PREVIEW = ROOT / "assets" / "national_flags_preview.png"

# PAL0 slots installed by flag_data_apply_palette().
W, R, B, Y, K, C, G, O = 1, 8, 9, 10, 11, 12, 13, 14
RGB = {
    W: (248, 248, 248), R: (216, 40, 48), B: (32, 72, 176),
    Y: (248, 200, 32), K: (16, 16, 24), C: (112, 192, 232),
    G: (24, 144, 72), O: (232, 112, 24),
}


def blank(color):
    return [[color for _ in range(16)] for _ in range(8)]


def horizontal(colors):
    p = blank(colors[-1])
    for y in range(8):
        band = min(len(colors) - 1, y * len(colors) // 8)
        p[y] = [colors[band]] * 16
    return p


def vertical(colors):
    p = blank(colors[-1])
    for y in range(8):
        for x in range(16):
            p[y][x] = colors[min(len(colors) - 1, x * len(colors) // 16)]
    return p


flags = []

# Spain
p = blank(Y)
for y in (0, 1, 6, 7): p[y] = [R] * 16
p[3][5] = p[4][5] = O
flags.append(p)

# Argentina
p = horizontal((C, W, C))
p[3][7] = p[3][8] = p[4][7] = p[4][8] = Y
flags.append(p)

# France
flags.append(vertical((B, W, R)))

# England
p = blank(W)
for y in range(8): p[y][7] = p[y][8] = R
for x in range(16): p[3][x] = p[4][x] = R
flags.append(p)

# Brazil
p = blank(G)
for y in range(1, 7):
    half = 2 + min(y, 7 - y)
    for x in range(8 - half, 8 + half): p[y][x] = Y
for y in range(2, 6):
    for x in range(6, 10): p[y][x] = B
flags.append(p)

# Morocco
p = blank(R)
for x, y in ((7,2),(8,2),(6,3),(9,3),(7,4),(8,4),(6,5),(9,5)):
    p[y][x] = G
flags.append(p)

# Portugal
p = blank(R)
for y in range(8):
    for x in range(6): p[y][x] = G
for x, y in ((5,3),(6,3),(5,4),(6,4)): p[y][x] = Y
flags.append(p)

# Belgium
flags.append(vertical((K, Y, R)))

# Netherlands
flags.append(horizontal((R, W, B)))

# Mexico
p = vertical((G, W, R))
p[3][7] = p[3][8] = p[4][7] = p[4][8] = O
flags.append(p)


def encode_tile(pixels, x0):
    rows = []
    for y in range(8):
        value = 0
        for x in range(x0, x0 + 8): value = (value << 4) | pixels[y][x]
        rows.append(value)
    return rows


lines = ["/* Generated by tools/build_flag_tiles.py. Ranking order in teams.c. */",
         "static const u32 flag_tiles[NUM_TEAMS * 2][8] = {"]
for flag in flags:
    for x0 in (0, 8):
        values = ", ".join(f"0x{value:08x}" for value in encode_tile(flag, x0))
        lines.append(f"    {{ {values} }},")
lines.append("};")

# A crisp 2x nearest-neighbour version for the selected-team showcase.
# The hardware cannot scale sprites or tiles, so the larger flags are real
# pre-authored 32x16 tile data rather than a blurry runtime approximation.
lines.append("static const u32 flag_large_tiles[NUM_TEAMS * 8][8] = {")
for flag in flags:
    large = [[flag[y // 2][x // 2] for x in range(32)] for y in range(16)]
    # Genesis multi-tile ordering is column-major, matching the draw loop.
    for tx in range(4):
        for ty in range(2):
            rows = []
            for y in range(ty * 8, ty * 8 + 8):
                value = 0
                for x in range(tx * 8, tx * 8 + 8):
                    value = (value << 4) | large[y][x]
                rows.append(value)
            values = ", ".join(f"0x{value:08x}" for value in rows)
            lines.append(f"    {{ {values} }},")
lines.append("};")
OUTPUT.write_text("\n".join(lines) + "\n", encoding="ascii")

preview = Image.new("RGB", (5 * 22, 2 * 14), (24, 40, 72))
for i, flag in enumerate(flags):
    fx, fy = (i % 5) * 22 + 3, (i // 5) * 14 + 3
    for y in range(8):
        for x in range(16): preview.putpixel((fx + x, fy + y), RGB[flag[y][x]])
preview.resize((880, 224), Image.Resampling.NEAREST).save(PREVIEW)
print(f"Wrote {OUTPUT}")
print(f"Wrote {PREVIEW}")
