WAV crowd_bed         "audio/crowd_bed.wav"         XGM
WAV crowd_chant       "audio/crowd_chant.wav"       XGM
WAV crowd_throw       "audio/crowd_throw.wav"       XGM
WAV crowd_elimination "audio/crowd_elimination.wav" XGM
WAV crowd_round       "audio/crowd_round.wav"       XGM
WAV crowd_gameover    "audio/crowd_gameover.wav"    XGM
WAV sfx_throw         "audio/throw.wav"             XGM
WAV sfx_pickup        "audio/pickup.wav"            XGM
WAV sfx_hit           "audio/hit.wav"               XGM
WAV sfx_bounce        "audio/bounce.wav"            XGM
WAV sfx_whistle       "audio/whistle.wav"           XGM
