"""Build the compact 16-colour tile art used by the game title screen."""

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "title_tiles.inc"
PREVIEW = ROOT / "assets" / "title_screen_preview.png"

# A deliberately chunky 5x7 arcade alphabet. Each source pixel becomes 2x2,
# then receives a one-pixel cream outline and navy drop shadow in a 16x16 cell.
FONT = {
    "A": ("01110", "10001", "10001", "11111", "10001", "10001", "10001"),
    "B": ("11110", "10001", "10001", "11110", "10001", "10001", "11110"),
    "C": ("01111", "10000", "10000", "10000", "10000", "10000", "01111"),
    "D": ("11110", "10001", "10001", "10001", "10001", "10001", "11110"),
    "E": ("11111", "10000", "10000", "11110", "10000", "10000", "11111"),
    "G": ("01111", "10000", "10000", "10111", "10001", "10001", "01111"),
    "I": ("11111", "00100", "00100", "00100", "00100", "00100", "11111"),
    "L": ("10000", "10000", "10000", "10000", "10000", "10000", "11111"),
    "M": ("10001", "11011", "10101", "10101", "10001", "10001", "10001"),
    "O": ("01110", "10001", "10001", "10001", "10001", "10001", "01110"),
    "R": ("11110", "10001", "10001", "11110", "10100", "10010", "10001"),
    "T": ("11111", "00100", "00100", "00100", "00100", "00100", "00100"),
}

TRANSPARENT, NAVY, BLUE, WHITE, YELLOW, ORANGE, RED, CYAN = range(8)
RGB = [
    (4, 8, 24), (8, 16, 48), (20, 48, 104), (248, 240, 208),
    (248, 216, 40), (240, 112, 24), (208, 32, 40), (64, 184, 232),
]


def glyph(letter):
    px = [[TRANSPARENT] * 16 for _ in range(16)]
    mask = [[False] * 16 for _ in range(16)]
    for sy, row in enumerate(FONT[letter]):
        for sx, bit in enumerate(row):
            if bit == "1":
                for yy in range(2):
                    for xx in range(2):
                        mask[1 + sy * 2 + yy][2 + sx * 2 + xx] = True
    # Shadow, outline, then a yellow-to-orange face.
    for y in range(16):
        for x in range(16):
            if mask[y][x] and x + 2 < 16 and y + 2 < 16:
                px[y + 2][x + 2] = NAVY
    for y in range(16):
        for x in range(16):
            if not mask[y][x]:
                continue
            for dy in (-1, 0, 1):
                for dx in (-1, 0, 1):
                    xx, yy = x + dx, y + dy
                    if 0 <= xx < 16 and 0 <= yy < 16:
                        px[yy][xx] = WHITE
    for y in range(16):
        for x in range(16):
            if mask[y][x]:
                px[y][x] = YELLOW if y < 8 else ORANGE
    return px


def ball():
    px = [[TRANSPARENT] * 32 for _ in range(32)]
    cx = cy = 15.5
    for y in range(32):
        for x in range(32):
            d2 = (x - cx) ** 2 + (y - cy) ** 2
            if d2 <= 14.5 ** 2:
                px[y][x] = WHITE
            if 9.0 ** 2 <= d2 <= 14.5 ** 2:
                px[y][x] = CYAN if x + y < 31 else BLUE
    # A readable low-resolution football panel and seams.
    for x, y in ((14,11),(15,10),(16,11),(17,12),(16,14),(14,14),(13,12)):
        px[y][x] = NAVY
    for x, y in ((10,7),(9,8),(8,9),(21,8),(22,9),(23,10),
                 (8,21),(9,22),(10,23),(21,23),(22,22),(23,21)):
        px[y][x] = NAVY
    for x in range(5, 27):
        y = 15 - (x - 5) // 7
        if 0 <= y < 32: px[y][x] = RED
    return px


def encode_tile(px, x0, y0):
    rows = []
    for y in range(y0, y0 + 8):
        value = 0
        for x in range(x0, x0 + 8):
            value = (value << 4) | px[y][x]
        rows.append(value)
    return rows


letters = "ABCDEGILMORT"
tiles = []
for letter in letters:
    p = glyph(letter)
    for tx in range(2):
        for ty in range(2):
            tiles.append(encode_tile(p, tx * 8, ty * 8))

ball_px = ball()
for tx in range(4):
    for ty in range(4):
        tiles.append(encode_tile(ball_px, tx * 8, ty * 8))

lines = [
    "/* Generated by tools/build_title_tiles.py. */",
    f"#define TITLE_GLYPH_COUNT {len(letters)}",
    f"#define TITLE_ART_TILE_COUNT {len(tiles)}",
    f'static const char title_glyph_order[] = "{letters}";',
    "static const u32 title_art_tiles[TITLE_ART_TILE_COUNT][8] = {",
]
for tile in tiles:
    lines.append("    { " + ", ".join(f"0x{v:08x}" for v in tile) + " },")
lines.append("};")
OUTPUT.write_text("\n".join(lines) + "\n", encoding="ascii")

# Preview the title composition at native Mega Drive resolution.
preview = Image.new("RGB", (320, 224), RGB[TRANSPARENT])
for y in range(224):
    shade = RGB[NAVY] if y < 184 else (3, 6, 18)
    for x in range(320): preview.putpixel((x, y), shade)

def paste_word(word, y):
    width = len(word) * 16 + (len(word) - 1) * 4
    x0 = (320 - width) // 2
    for i, ch in enumerate(word):
        p = glyph(ch)
        for yy in range(16):
            for xx in range(16):
                if p[yy][xx]: preview.putpixel((x0 + i * 20 + xx, y + yy), RGB[p[yy][xx]])

paste_word("MICRO", 32)
paste_word("RETRO", 58)
paste_word("DODGEBALL", 88)
for y in range(32):
    for x in range(32):
        if ball_px[y][x]: preview.putpixel((250 + x, 115 + y), RGB[ball_px[y][x]])
preview.save(PREVIEW)
print(f"Wrote {OUTPUT}")
print(f"Wrote {PREVIEW}")
